language: php

php:
  - 7.1
  - 7.2
  - 7.3

services:
  - docker

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - docker-compose up -d
  - travis_retry composer self-update
  - travis_retry composer update --no-progress --no-interaction --prefer-dist
  - sleep 10

script:
  - composer test
